version: 2.1

orbs:
  android: circleci/android@2.0.0  # Ensure to use a recent version of the Android orb

jobs:
  build:
    docker:
      - image: cimg/android:2023.04  # Docker image with Android environment
    steps:
      - checkout  # Checks out the source code
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ epoch }}
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Build
          command: ./gradlew assembleDebug  # Adjust this command based on your project's specific build requirements
      - store_artifacts:
          path: app/build/outputs/
          destination: build_outputs
      - run:
          name: Authenticate with Firebase
          command: echo $FIREBASE_TOKEN | firebase login:ci --token
      - run:
          name: Deploy APK to Firebase
          command: firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk --app $FIREBASE_APP_ID --token $FIREBASE_TOKEN --groups "testers"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
